<?php

/*
 * This file is part of the Composer Puli Plugin.
 *
 * (c) Bernhard Schussek <bschussek@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Puli\Extension\Composer\RepositoryDumper;

use Composer\Installer\InstallationManager;
use Composer\Package\PackageInterface;
use Composer\Util\Filesystem;
use Puli\Extension\Composer\RepositoryBuilder\RepositoryBuilder;
use Puli\Filesystem\PhpCacheRepository;
use Puli\Repository\ResourceRepository;

/**
 * Dumps a resource repository based on the Composer configuration.
 *
 * @since  1.0
 * @author Bernhard Schussek <bschussek@gmail.com>
 */
class RepositoryDumper
{
    /**
     * @var string
     */
    private $vendorDir;

    /**
     * @var PackageInterface
     */
    private $projectPackage;

    /**
     * @var PackageInterface[]
     */
    private $installedPackages;

    /**
     * @var RepositoryBuilder
     */
    private $repoBuilder;

    public function setVendorDir($vendorDir)
    {
        $this->vendorDir = $vendorDir;
    }

    public function setProjectPackage(PackageInterface $package)
    {
        $this->projectPackage = $package;
    }

    public function setInstalledPackages(array $packages)
    {
        $this->installedPackages = $packages;
    }

    public function setRepositoryBuilder(RepositoryBuilder $repoLoader)
    {
        $this->repoBuilder = $repoLoader;
    }

    public function dumpRepository()
    {
        $repo = new ResourceRepository();
        $filesystem = new Filesystem();
        $filesystem->ensureDirectoryExists($this->vendorDir);
        $vendorPath = $filesystem->normalizePath(realpath($this->vendorDir));

        $this->repoBuilder->loadPackage($this->projectPackage);

        foreach ($this->installedPackages as $package) {
            /** @var \Composer\Package\PackageInterface $package */
            $this->repoBuilder->loadPackage($package);
        }

        $this->repoBuilder->buildRepository($repo);

        $filesystem->ensureDirectoryExists($vendorPath.'/composer');

        PhpCacheRepository::dumpRepository($repo, $vendorPath.'/composer');

        $locatorCode = <<<LOCATOR
<?php

// resource-repository.php @generated by the Composer Puli plugin

use Puli\Filesystem\PhpCacheRepository;

return new PhpCacheRepository(__DIR__.'/composer');

LOCATOR;

        file_put_contents($vendorPath.'/resource-repository.php', $locatorCode);
    }
}
