language: php

matrix:
    include:
        - php: hhvm
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: nightly
    allow_failures:
        - php: hhvm
        - php: nightly
    fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install: composer install -n

script: vendor/bin/phpunit -v --coverage-clover=coverage.clover

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'

notifications:
  webhooks:
    urls: ['https://webhooks.gitter.im/e/9ccc2378e6c0de6480f8']
    on_success: change
    on_failure: always
    on_start:   never
